# Generated by Django 4.2.7 on 2023-11-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abtName', models.CharField(max_length=25)),
                ('abtFirstname', models.CharField(max_length=25)),
                ('abtText', models.CharField(max_length=500)),
                ('abtCompetencies', models.CharField(max_length=255)),
            ],
        ),
    ]
