# Generated by Django 4.2.7 on 2023-11-09 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commPosted_date', models.DateField()),
                ('commEdited_date', models.DateField()),
                ('commTextmessage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persName', models.CharField(max_length=25)),
                ('persFirstname', models.CharField(max_length=25)),
                ('persText', models.TextField()),
                ('persCompetencies', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjName', models.CharField(max_length=128)),
                ('subjCreationDate', models.DateField()),
                ('subjEdited_date', models.DateField()),
                ('subjTextmessage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AboutMe',
        ),
        migrations.AddField(
            model_name='commentblog',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subjectblog'),
        ),
    ]
